INSERT INTO category_expense (category, description_category_expense) VALUES
    ('Eletrodomésticos', 'Compra de aparelhos eletrodomésticos'),
    ('Impostos', 'Pagamento de impostos e taxas'),
    ('Doações', 'Contribuições para causas sociais e doações'),
    ('Seguro', 'Prêmios de seguro para proteção pessoal e de propriedade'),
    ('Manutenção', 'Custos de manutenção para casa e veículos'),
    ('Energia', 'Despesas com fornecimento de energia elétrica'),
    ('Telecomunicações', 'Gastos com serviços de telecomunicações'),
    ('Animais de Estimação', 'Cuidados e despesas relacionadas a animais de estimação'),
    ('Presentes', 'Compras de presentes para ocasiões especiais'),
    ('Serviços Bancários', 'Taxas e serviços relacionados a instituições financeiras'),
    ('Condomínio', 'Despesas relacionadas ao condomínio residencial'),
    ('Café e Restaurantes', 'Gastos em cafeterias e restaurantes'),
    ('Material de Escritório', 'Compra de suprimentos de escritório'),
    ('Crianças', 'Despesas relacionadas a cuidados e educação de crianças'),
    ('Hobbies', 'Custos relacionados a hobbies e atividades recreativas'),
    ('Beleza', 'Produtos e serviços de beleza e cuidado pessoal'),
    ('Comunicação', 'Despesas com comunicação, como correios e mensagens'),
    ('Arte e Cultura', 'Gastos relacionados a eventos culturais e artísticos'),
    ('Compras Online', 'Compras realizadas pela internet'),
    ('Equipamentos Esportivos', 'Compra de equipamentos para atividades esportivas');
